services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    restart: unless-stopped
    environment:
      DB_SERVER: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 0
      PS_SSL_ENABLED: 0
      PS_SSL_ENABLED_EVERYWHERE: 0
      PS_DOMAIN: localhost:8099
      ADMIN_MAIL: admin@example.com
      ADMIN_PASSWD: ${ADMIN_PASSWORD}
    ports:
      - '8099:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./prestashop_data:/var/www/html
      - ./prestashop_img:/var/www/html/img
      - ./prestashop_modules:/var/www/html/modules
      - ./mzc_landing_newsletter:/var/www/html/modules/mzc_landing_newsletter
    networks:
      - prestashop-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10
    container_name: prestashop_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-p${MYSQL_ROOT_PASSWORD}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop-net

networks:
  prestashop-net:

volumes:
  prestashop_data:
  prestashop_img:
  prestashop_modules:
  db_data:
