services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop_clean
    restart: unless-stopped
    environment:
      DB_SERVER: db
      DB_NAME: ${MYSQL_DATABASE_TEST}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 0
      PS_SSL_ENABLED: 0
      PS_SSL_ENABLED_EVERYWHERE: 0
      PS_DEV_MODE: 1
      PS_DOMAIN: localhost:8199
      ADMIN_MAIL: admin@example.com
      ADMIN_PASSWD: ${ADMIN_PASSWORD}
    ports:
      - '8199:80'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - prestashop-net-test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10
    container_name: prestashop_db_clean
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE_TEST}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-p${MYSQL_ROOT_PASSWORD}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prestashop-net-test

networks:
  prestashop-net-test:
